//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="TransactionWindowInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class TransactionWindowInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private System.Nullable<System.DateTime> EndDateField;
    
    private int GroupIdField;
    
    private int IdField;
    
    private bool IsClosedField;
    
    private bool IsPrimaryField;
    
    private string NameField;
    
    private System.DateTime StartDateField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Nullable<System.DateTime> EndDate
    {
        get
        {
            return this.EndDateField;
        }
        set
        {
            this.EndDateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int GroupId
    {
        get
        {
            return this.GroupIdField;
        }
        set
        {
            this.GroupIdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Id
    {
        get
        {
            return this.IdField;
        }
        set
        {
            this.IdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsClosed
    {
        get
        {
            return this.IsClosedField;
        }
        set
        {
            this.IsClosedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsPrimary
    {
        get
        {
            return this.IsPrimaryField;
        }
        set
        {
            this.IsPrimaryField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime StartDate
    {
        get
        {
            return this.StartDateField;
        }
        set
        {
            this.StartDateField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class GroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string DescriptionField;
    
    private int IdField;
    
    private string NameField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Description
    {
        get
        {
            return this.DescriptionField;
        }
        set
        {
            this.DescriptionField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Id
    {
        get
        {
            return this.IdField;
        }
        set
        {
            this.IdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ImageData", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ImageData : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private byte[] DataField;
    
    private int IdField;
    
    private string NameField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public byte[] Data
    {
        get
        {
            return this.DataField;
        }
        set
        {
            this.DataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Id
    {
        get
        {
            return this.IdField;
        }
        set
        {
            this.IdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PagedDataRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PagedDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int EndRowField;
    
    private int StartRowField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int EndRow
    {
        get
        {
            return this.EndRowField;
        }
        set
        {
            this.EndRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int StartRow
    {
        get
        {
            return this.StartRowField;
        }
        set
        {
            this.StartRowField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PagedDataOfUserInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PagedDataOfUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private UserInfo[] DataField;
    
    private int EndRowField;
    
    private int StartRowField;
    
    private int TotalRowsField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public UserInfo[] Data
    {
        get
        {
            return this.DataField;
        }
        set
        {
            this.DataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int EndRow
    {
        get
        {
            return this.EndRowField;
        }
        set
        {
            this.EndRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int StartRow
    {
        get
        {
            return this.StartRowField;
        }
        set
        {
            this.StartRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int TotalRows
    {
        get
        {
            return this.TotalRowsField;
        }
        set
        {
            this.TotalRowsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string FirstNameField;
    
    private int IdField;
    
    private bool IsSAField;
    
    private string LastNameField;
    
    private string UsernameField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string FirstName
    {
        get
        {
            return this.FirstNameField;
        }
        set
        {
            this.FirstNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Id
    {
        get
        {
            return this.IdField;
        }
        set
        {
            this.IdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsSA
    {
        get
        {
            return this.IsSAField;
        }
        set
        {
            this.IsSAField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LastName
    {
        get
        {
            return this.LastNameField;
        }
        set
        {
            this.LastNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Username
    {
        get
        {
            return this.UsernameField;
        }
        set
        {
            this.UsernameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PagedDataOfGroupInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PagedDataOfGroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private GroupInfo[] DataField;
    
    private int EndRowField;
    
    private int StartRowField;
    
    private int TotalRowsField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public GroupInfo[] Data
    {
        get
        {
            return this.DataField;
        }
        set
        {
            this.DataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int EndRow
    {
        get
        {
            return this.EndRowField;
        }
        set
        {
            this.EndRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int StartRow
    {
        get
        {
            return this.StartRowField;
        }
        set
        {
            this.StartRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int TotalRows
    {
        get
        {
            return this.TotalRowsField;
        }
        set
        {
            this.TotalRowsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PermissionInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PermissionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private int GroupIDField;
    
    private string GroupNameField;
    
    private string PermissionField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int GroupID
    {
        get
        {
            return this.GroupIDField;
        }
        set
        {
            this.GroupIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string GroupName
    {
        get
        {
            return this.GroupNameField;
        }
        set
        {
            this.GroupNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Permission
    {
        get
        {
            return this.PermissionField;
        }
        set
        {
            this.PermissionField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="SubExpenceInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class SubExpenceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private decimal ASEPSA_AmountField;
    
    private decimal AmountSubtotalField;
    
    private decimal AmountTotalField;
    
    private string DescriptionField;
    
    private int ExpenseIDField;
    
    private int IDField;
    
    private string NameField;
    
    private bool SplitIssuedField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal ASEPSA_Amount
    {
        get
        {
            return this.ASEPSA_AmountField;
        }
        set
        {
            this.ASEPSA_AmountField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal AmountSubtotal
    {
        get
        {
            return this.AmountSubtotalField;
        }
        set
        {
            this.AmountSubtotalField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal AmountTotal
    {
        get
        {
            return this.AmountTotalField;
        }
        set
        {
            this.AmountTotalField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Description
    {
        get
        {
            return this.DescriptionField;
        }
        set
        {
            this.DescriptionField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ExpenseID
    {
        get
        {
            return this.ExpenseIDField;
        }
        set
        {
            this.ExpenseIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ID
    {
        get
        {
            return this.IDField;
        }
        set
        {
            this.IDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool SplitIssued
    {
        get
        {
            return this.SplitIssuedField;
        }
        set
        {
            this.SplitIssuedField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ExpenceInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class ExpenceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private decimal AmountField;
    
    private string CategoryField;
    
    private System.DateTime DateEnteredField;
    
    private System.Nullable<System.DateTime> DateFinalizedField;
    
    private System.DateTime DateOfExpenseField;
    
    private string DescriptionField;
    
    private int GroupIDField;
    
    private int IDField;
    
    private int[] ImagesField;
    
    private string NameField;
    
    private int StatusField;
    
    private SubExpenceInfo[] SubExpensesField;
    
    private int TransactionWindowField;
    
    private int UserIDField;
    
    private bool UsesASEPSAField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal Amount
    {
        get
        {
            return this.AmountField;
        }
        set
        {
            this.AmountField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Category
    {
        get
        {
            return this.CategoryField;
        }
        set
        {
            this.CategoryField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateEntered
    {
        get
        {
            return this.DateEnteredField;
        }
        set
        {
            this.DateEnteredField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Nullable<System.DateTime> DateFinalized
    {
        get
        {
            return this.DateFinalizedField;
        }
        set
        {
            this.DateFinalizedField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateOfExpense
    {
        get
        {
            return this.DateOfExpenseField;
        }
        set
        {
            this.DateOfExpenseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Description
    {
        get
        {
            return this.DescriptionField;
        }
        set
        {
            this.DescriptionField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int GroupID
    {
        get
        {
            return this.GroupIDField;
        }
        set
        {
            this.GroupIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ID
    {
        get
        {
            return this.IDField;
        }
        set
        {
            this.IDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int[] Images
    {
        get
        {
            return this.ImagesField;
        }
        set
        {
            this.ImagesField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Status
    {
        get
        {
            return this.StatusField;
        }
        set
        {
            this.StatusField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public SubExpenceInfo[] SubExpenses
    {
        get
        {
            return this.SubExpensesField;
        }
        set
        {
            this.SubExpensesField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int TransactionWindow
    {
        get
        {
            return this.TransactionWindowField;
        }
        set
        {
            this.TransactionWindowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int UserID
    {
        get
        {
            return this.UserIDField;
        }
        set
        {
            this.UserIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool UsesASEPSA
    {
        get
        {
            return this.UsesASEPSAField;
        }
        set
        {
            this.UsesASEPSAField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="TransactionInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class TransactionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private decimal AmountField;
    
    private System.Nullable<System.DateTime> ApprovalDateField;
    
    private System.DateTime DateOfExpenseField;
    
    private int ForExpenseField;
    
    private string ForExpenseNameField;
    
    private int ForSubExpenceField;
    
    private string ForSubExpenceNameField;
    
    private int FromUserField;
    
    private string FromUserNameField;
    
    private int IDField;
    
    private decimal PercentOfExpenseField;
    
    private decimal PercentOfSubExpenseField;
    
    private int StatusField;
    
    private int ToUserField;
    
    private string ToUserNameField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal Amount
    {
        get
        {
            return this.AmountField;
        }
        set
        {
            this.AmountField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Nullable<System.DateTime> ApprovalDate
    {
        get
        {
            return this.ApprovalDateField;
        }
        set
        {
            this.ApprovalDateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateOfExpense
    {
        get
        {
            return this.DateOfExpenseField;
        }
        set
        {
            this.DateOfExpenseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ForExpense
    {
        get
        {
            return this.ForExpenseField;
        }
        set
        {
            this.ForExpenseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ForExpenseName
    {
        get
        {
            return this.ForExpenseNameField;
        }
        set
        {
            this.ForExpenseNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ForSubExpence
    {
        get
        {
            return this.ForSubExpenceField;
        }
        set
        {
            this.ForSubExpenceField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ForSubExpenceName
    {
        get
        {
            return this.ForSubExpenceNameField;
        }
        set
        {
            this.ForSubExpenceNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int FromUser
    {
        get
        {
            return this.FromUserField;
        }
        set
        {
            this.FromUserField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string FromUserName
    {
        get
        {
            return this.FromUserNameField;
        }
        set
        {
            this.FromUserNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ID
    {
        get
        {
            return this.IDField;
        }
        set
        {
            this.IDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal PercentOfExpense
    {
        get
        {
            return this.PercentOfExpenseField;
        }
        set
        {
            this.PercentOfExpenseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public decimal PercentOfSubExpense
    {
        get
        {
            return this.PercentOfSubExpenseField;
        }
        set
        {
            this.PercentOfSubExpenseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Status
    {
        get
        {
            return this.StatusField;
        }
        set
        {
            this.StatusField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ToUser
    {
        get
        {
            return this.ToUserField;
        }
        set
        {
            this.ToUserField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ToUserName
    {
        get
        {
            return this.ToUserNameField;
        }
        set
        {
            this.ToUserNameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PagedDataOfTransactionWindowInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PagedDataOfTransactionWindowInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private TransactionWindowInfo[] DataField;
    
    private int EndRowField;
    
    private int StartRowField;
    
    private int TotalRowsField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public TransactionWindowInfo[] Data
    {
        get
        {
            return this.DataField;
        }
        set
        {
            this.DataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int EndRow
    {
        get
        {
            return this.EndRowField;
        }
        set
        {
            this.EndRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int StartRow
    {
        get
        {
            return this.StartRowField;
        }
        set
        {
            this.StartRowField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int TotalRows
    {
        get
        {
            return this.TotalRowsField;
        }
        set
        {
            this.TotalRowsField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService", SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOpenTransactionWindows", ReplyAction="http://tempuri.org/IService/GetOpenTransactionWindowsResponse")]
    TransactionWindowInfo[] GetOpenTransactionWindows(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OpenTransactionWindow", ReplyAction="http://tempuri.org/IService/OpenTransactionWindowResponse")]
    int OpenTransactionWindow(int groupId, string Name, bool isPrimary, System.Nullable<System.DateTime> startDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetPrimaryTransactionWindow", ReplyAction="http://tempuri.org/IService/SetPrimaryTransactionWindowResponse")]
    void SetPrimaryTransactionWindow(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CloseTransactionWindow", ReplyAction="http://tempuri.org/IService/CloseTransactionWindowResponse")]
    void CloseTransactionWindow(int id, bool AutoTransfer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroupsForUser", ReplyAction="http://tempuri.org/IService/GetGroupsForUserResponse")]
    GroupInfo[] GetGroupsForUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AcceptTransaction", ReplyAction="http://tempuri.org/IService/AcceptTransactionResponse")]
    void AcceptTransaction(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RejectTransaction", ReplyAction="http://tempuri.org/IService/RejectTransactionResponse")]
    void RejectTransaction(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReIssueTransaction", ReplyAction="http://tempuri.org/IService/ReIssueTransactionResponse")]
    void ReIssueTransaction(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RevokeTransaction", ReplyAction="http://tempuri.org/IService/RevokeTransactionResponse")]
    void RevokeTransaction(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ForceAccpetAllTransactionsInWindow", ReplyAction="http://tempuri.org/IService/ForceAccpetAllTransactionsInWindowResponse")]
    void ForceAccpetAllTransactionsInWindow(int window);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PostImageToExpense", ReplyAction="http://tempuri.org/IService/PostImageToExpenseResponse")]
    int PostImageToExpense(string name, byte[] data, int expenseID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImage", ReplyAction="http://tempuri.org/IService/GetImageResponse")]
    ImageData GetImage(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UsernamePasswordAuthenticate", ReplyAction="http://tempuri.org/IService/UsernamePasswordAuthenticateResponse")]
    bool UsernamePasswordAuthenticate(string Username, string Password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangePassword", ReplyAction="http://tempuri.org/IService/ChangePasswordResponse")]
    void ChangePassword(string newPassword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
    PagedDataOfUserInfo GetAllUsers(PagedDataRequest pdr);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsersInGroup", ReplyAction="http://tempuri.org/IService/GetAllUsersInGroupResponse")]
    UserInfo[] GetAllUsersInGroup(int groupId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ForceAcceptAllTransactions", ReplyAction="http://tempuri.org/IService/ForceAcceptAllTransactionsResponse")]
    void ForceAcceptAllTransactions(int expenseId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CurrentUser", ReplyAction="http://tempuri.org/IService/CurrentUserResponse")]
    UserInfo CurrentUser();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroup", ReplyAction="http://tempuri.org/IService/GetGroupResponse")]
    GroupInfo GetGroup(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGroup", ReplyAction="http://tempuri.org/IService/CreateGroupResponse")]
    int CreateGroup(string name, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllGroups", ReplyAction="http://tempuri.org/IService/GetAllGroupsResponse")]
    PagedDataOfGroupInfo GetAllGroups(PagedDataRequest pdr);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateGroup", ReplyAction="http://tempuri.org/IService/UpdateGroupResponse")]
    void UpdateGroup(int id, string name, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
    int CreateUser(string userName, string password, string firstName, string lastName, int fbid, int groupID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
    void UpdateUser(int userid, string username, string password, string firstName, string lastName, System.Nullable<int> fbid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
    UserInfo GetUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Grant", ReplyAction="http://tempuri.org/IService/GrantResponse")]
    void Grant(int userID, int groupID, string permission);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Deny", ReplyAction="http://tempuri.org/IService/DenyResponse")]
    void Deny(int userID, int groupID, string permission);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPermissions", ReplyAction="http://tempuri.org/IService/GetPermissionsResponse")]
    PermissionInfo[] GetPermissions(int userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateExpence", ReplyAction="http://tempuri.org/IService/CreateExpenceResponse")]
    int CreateExpence(string name, string description, decimal total, System.DateTime dateOfExpense, int userID, bool useASEPSA, int groupID, string category, int transactionWindow);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InvalidateExpence", ReplyAction="http://tempuri.org/IService/InvalidateExpenceResponse")]
    bool InvalidateExpence(int expenseID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSubExpense", ReplyAction="http://tempuri.org/IService/AddSubExpenseResponse")]
    int AddSubExpense(int expenseID, decimal amount, string name, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSubExpense", ReplyAction="http://tempuri.org/IService/GetSubExpenseResponse")]
    SubExpenceInfo GetSubExpense(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveSubExpense", ReplyAction="http://tempuri.org/IService/RemoveSubExpenseResponse")]
    bool RemoveSubExpense(int subExpenseID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetExpences", ReplyAction="http://tempuri.org/IService/GetExpencesResponse")]
    ExpenceInfo[] GetExpences(int groupID, int ownerID, System.DateTime from, System.DateTime to);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetExpence", ReplyAction="http://tempuri.org/IService/GetExpenceResponse")]
    ExpenceInfo GetExpence(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExpences", ReplyAction="http://tempuri.org/IService/GetAllExpencesResponse")]
    ExpenceInfo[] GetAllExpences(int groupID, System.DateTime from, System.DateTime to);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExpencesInWindow", ReplyAction="http://tempuri.org/IService/GetAllExpencesInWindowResponse")]
    ExpenceInfo[] GetAllExpencesInWindow(int groupID, int window);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FinalizeExpense", ReplyAction="http://tempuri.org/IService/FinalizeExpenseResponse")]
    void FinalizeExpense(int expenseID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SplitSubExpense", ReplyAction="http://tempuri.org/IService/SplitSubExpenseResponse")]
    void SplitSubExpense(int subexpenseID, System.Collections.Generic.Dictionary<int, decimal> UserToCostMap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RevokeSubExpenseSplit", ReplyAction="http://tempuri.org/IService/RevokeSubExpenseSplitResponse")]
    void RevokeSubExpenseSplit(int subexpenseID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSplitCosts", ReplyAction="http://tempuri.org/IService/GetSplitCostsResponse")]
    TransactionInfo[] GetSplitCosts(int groupID, int userID, int transactionWindow);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSplitPayments", ReplyAction="http://tempuri.org/IService/GetSplitPaymentsResponse")]
    TransactionInfo[] GetSplitPayments(int groupID, int userID, int transactionWindow);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTransactionWindows", ReplyAction="http://tempuri.org/IService/GetTransactionWindowsResponse")]
    PagedDataOfTransactionWindowInfo GetTransactionWindows(int groupId, PagedDataRequest pdr);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTransactionWindow", ReplyAction="http://tempuri.org/IService/GetTransactionWindowResponse")]
    TransactionWindowInfo GetTransactionWindow(int id, int groupID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TransactionWindowInfo[] GetOpenTransactionWindows(int groupId)
    {
        return base.Channel.GetOpenTransactionWindows(groupId);
    }
    
    public int OpenTransactionWindow(int groupId, string Name, bool isPrimary, System.Nullable<System.DateTime> startDate)
    {
        return base.Channel.OpenTransactionWindow(groupId, Name, isPrimary, startDate);
    }
    
    public void SetPrimaryTransactionWindow(int id)
    {
        base.Channel.SetPrimaryTransactionWindow(id);
    }
    
    public void CloseTransactionWindow(int id, bool AutoTransfer)
    {
        base.Channel.CloseTransactionWindow(id, AutoTransfer);
    }
    
    public GroupInfo[] GetGroupsForUser(int id)
    {
        return base.Channel.GetGroupsForUser(id);
    }
    
    public void AcceptTransaction(int id)
    {
        base.Channel.AcceptTransaction(id);
    }
    
    public void RejectTransaction(int id)
    {
        base.Channel.RejectTransaction(id);
    }
    
    public void ReIssueTransaction(int id)
    {
        base.Channel.ReIssueTransaction(id);
    }
    
    public void RevokeTransaction(int id)
    {
        base.Channel.RevokeTransaction(id);
    }
    
    public void ForceAccpetAllTransactionsInWindow(int window)
    {
        base.Channel.ForceAccpetAllTransactionsInWindow(window);
    }
    
    public int PostImageToExpense(string name, byte[] data, int expenseID)
    {
        return base.Channel.PostImageToExpense(name, data, expenseID);
    }
    
    public ImageData GetImage(int id)
    {
        return base.Channel.GetImage(id);
    }
    
    public bool UsernamePasswordAuthenticate(string Username, string Password)
    {
        return base.Channel.UsernamePasswordAuthenticate(Username, Password);
    }
    
    public void ChangePassword(string newPassword)
    {
        base.Channel.ChangePassword(newPassword);
    }
    
    public PagedDataOfUserInfo GetAllUsers(PagedDataRequest pdr)
    {
        return base.Channel.GetAllUsers(pdr);
    }
    
    public UserInfo[] GetAllUsersInGroup(int groupId)
    {
        return base.Channel.GetAllUsersInGroup(groupId);
    }
    
    public void ForceAcceptAllTransactions(int expenseId)
    {
        base.Channel.ForceAcceptAllTransactions(expenseId);
    }
    
    public UserInfo CurrentUser()
    {
        return base.Channel.CurrentUser();
    }
    
    public GroupInfo GetGroup(int id)
    {
        return base.Channel.GetGroup(id);
    }
    
    public int CreateGroup(string name, string description)
    {
        return base.Channel.CreateGroup(name, description);
    }
    
    public PagedDataOfGroupInfo GetAllGroups(PagedDataRequest pdr)
    {
        return base.Channel.GetAllGroups(pdr);
    }
    
    public void UpdateGroup(int id, string name, string description)
    {
        base.Channel.UpdateGroup(id, name, description);
    }
    
    public int CreateUser(string userName, string password, string firstName, string lastName, int fbid, int groupID)
    {
        return base.Channel.CreateUser(userName, password, firstName, lastName, fbid, groupID);
    }
    
    public void UpdateUser(int userid, string username, string password, string firstName, string lastName, System.Nullable<int> fbid)
    {
        base.Channel.UpdateUser(userid, username, password, firstName, lastName, fbid);
    }
    
    public UserInfo GetUser(int id)
    {
        return base.Channel.GetUser(id);
    }
    
    public void Grant(int userID, int groupID, string permission)
    {
        base.Channel.Grant(userID, groupID, permission);
    }
    
    public void Deny(int userID, int groupID, string permission)
    {
        base.Channel.Deny(userID, groupID, permission);
    }
    
    public PermissionInfo[] GetPermissions(int userID)
    {
        return base.Channel.GetPermissions(userID);
    }
    
    public int CreateExpence(string name, string description, decimal total, System.DateTime dateOfExpense, int userID, bool useASEPSA, int groupID, string category, int transactionWindow)
    {
        return base.Channel.CreateExpence(name, description, total, dateOfExpense, userID, useASEPSA, groupID, category, transactionWindow);
    }
    
    public bool InvalidateExpence(int expenseID)
    {
        return base.Channel.InvalidateExpence(expenseID);
    }
    
    public int AddSubExpense(int expenseID, decimal amount, string name, string description)
    {
        return base.Channel.AddSubExpense(expenseID, amount, name, description);
    }
    
    public SubExpenceInfo GetSubExpense(int id)
    {
        return base.Channel.GetSubExpense(id);
    }
    
    public bool RemoveSubExpense(int subExpenseID)
    {
        return base.Channel.RemoveSubExpense(subExpenseID);
    }
    
    public ExpenceInfo[] GetExpences(int groupID, int ownerID, System.DateTime from, System.DateTime to)
    {
        return base.Channel.GetExpences(groupID, ownerID, from, to);
    }
    
    public ExpenceInfo GetExpence(int id)
    {
        return base.Channel.GetExpence(id);
    }
    
    public ExpenceInfo[] GetAllExpences(int groupID, System.DateTime from, System.DateTime to)
    {
        return base.Channel.GetAllExpences(groupID, from, to);
    }
    
    public ExpenceInfo[] GetAllExpencesInWindow(int groupID, int window)
    {
        return base.Channel.GetAllExpencesInWindow(groupID, window);
    }
    
    public void FinalizeExpense(int expenseID)
    {
        base.Channel.FinalizeExpense(expenseID);
    }
    
    public void SplitSubExpense(int subexpenseID, System.Collections.Generic.Dictionary<int, decimal> UserToCostMap)
    {
        base.Channel.SplitSubExpense(subexpenseID, UserToCostMap);
    }
    
    public void RevokeSubExpenseSplit(int subexpenseID)
    {
        base.Channel.RevokeSubExpenseSplit(subexpenseID);
    }
    
    public TransactionInfo[] GetSplitCosts(int groupID, int userID, int transactionWindow)
    {
        return base.Channel.GetSplitCosts(groupID, userID, transactionWindow);
    }
    
    public TransactionInfo[] GetSplitPayments(int groupID, int userID, int transactionWindow)
    {
        return base.Channel.GetSplitPayments(groupID, userID, transactionWindow);
    }
    
    public PagedDataOfTransactionWindowInfo GetTransactionWindows(int groupId, PagedDataRequest pdr)
    {
        return base.Channel.GetTransactionWindows(groupId, pdr);
    }
    
    public TransactionWindowInfo GetTransactionWindow(int id, int groupID)
    {
        return base.Channel.GetTransactionWindow(id, groupID);
    }
}
